source 'https://rubygems.org'

gem 'rake', '~> 13.0'
gem 'rake_dependencies', '~> 2.3'
gem 'rake_terraform', '~> 1.5'
gem 'confidante', '~> 0.19'
gem 'lino', '~> 1.1'
gem 'rspec', '~> 3.9'
gem 'awspec', '~> 1.18'
gem 'git', '~> 1.5'
gem 'semantic', '~> 1.6'
