---
region: 'eu-west-2'

component: 'test'
deployment_identifier: "%{hiera('seed')}"

domain_name: 'infrablocks.click'

hosted_zone_id: "Z08829023L5IPIQBJOX63"
private_zone_id: 'Z0211739BXR21FNN139O'

record_set_name_template: "service-1.%{hiera('domain_name')}"
record_set_ip_type: 'private'

vpc_cidr: "10.1.0.0/16"
availability_zones:
  - "eu-west-2a"
  - "eu-west-2b"
private_network_cidr: '10.0.0.0/8'

cluster_name: 'test-cluster'
cluster_instance_ssh_public_key_path: "%{cwd}/config/secrets/keys/cluster/ssh.public"
cluster_instance_type: 't2.medium'
cluster_instance_ami: 'ami-3fb6bc5b'

cluster_minimum_size: 1
cluster_maximum_size: 3
cluster_desired_capacity: 2

service_task_container_definitions: ""
service_task_network_mode: "host"

service_name: "service-1"
service_image: "nginx"
service_command:
  - "nginx"
  - "-g"
  - "daemon off;"
service_port: 80
service_desired_count: 2
service_deployment_maximum_percent: 150
service_deployment_minimum_healthy_percent: 25
service_role: ''

attach_to_load_balancer: 'no'
