---
configuration_directory: "%{cwd}/examples/full"
state_file: "%{cwd}/state/full.tfstate"
vars:
  region: "%{hiera('region')}"
  availability_zones: "%{hiera('availability_zones')}"

  vpc_cidr: "%{hiera('vpc_cidr')}"
  private_network_cidr: "%{hiera('private_network_cidr')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  private_zone_id: "%{hiera('private_zone_id')}"

  cluster_name: "%{hiera('cluster_name')}"
  cluster_instance_ssh_public_key_path: "%{hiera('cluster_instance_ssh_public_key_path')}"
  cluster_instance_type: "%{hiera('cluster_instance_type')}"

  cluster_minimum_size: "%{hiera('cluster_minimum_size')}"
  cluster_maximum_size: "%{hiera('cluster_maximum_size')}"
  cluster_desired_capacity: "%{hiera('cluster_desired_capacity')}"

  service_task_container_definitions: "%{hiera('service_task_container_definitions')}"
  service_task_network_mode: "%{hiera('service_task_network_mode')}"

  service_name: "%{hiera('service_name')}"
  service_image: "%{hiera('service_image')}"
  service_command: "%{hiera('service_command')}"
  service_port: "%{hiera('service_port')}"
  service_role: "%{hiera('service_role')}"

  attach_to_load_balancer: "%{hiera('attach_to_load_balancer')}"

  record_set_name_template: "%{hiera('record_set_name_template')}"
  record_set_ip_type: "%{hiera('record_set_ip_type')}"
