---
source_directory: "spec/infra/prerequisites"
state_file: "%{hiera('project_directory')}/state/prerequisites.tfstate"
vars:
  vpc_cidr: "%{hiera('vpc_cidr')}"
  region: "%{hiera('region')}"
  availability_zones: "%{hiera('availability_zones')}"
  private_network_cidr: "%{hiera('private_network_cidr')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  private_zone_id: "%{hiera('private_zone_id')}"

  cluster_name: "%{hiera('cluster_name')}"
  cluster_instance_ssh_public_key_path: "%{hiera('cluster_instance_ssh_public_key_path')}"
  cluster_instance_type: "%{hiera('cluster_instance_type')}"

  cluster_minimum_size: "%{hiera('cluster_minimum_size')}"
  cluster_maximum_size: "%{hiera('cluster_maximum_size')}"
  cluster_desired_capacity: "%{hiera('cluster_desired_capacity')}"

  service_task_container_definitions: "%{hiera('service_task_container_definitions')}"
  service_task_network_mode: "%{hiera('service_task_network_mode')}"

  service_name: "%{hiera('service_name')}"
  service_image: "%{hiera('service_image')}"
  service_command: "%{hiera('service_command')}"
  service_port: "%{hiera('service_port')}"
  service_desired_count: "%{hiera('service_desired_count')}"
  service_deployment_maximum_percent: "%{hiera('service_deployment_maximum_percent')}"
  service_deployment_minimum_healthy_percent: "%{hiera('service_deployment_minimum_healthy_percent')}"
  service_role: "%{hiera('service_role')}"

  attach_to_load_balancer: "%{hiera('attach_to_load_balancer')}"

  service_certificate_body: "%{hiera('service_certificate_body')}"
  service_certificate_private_key: "%{hiera('service_certificate_private_key')}"

  service_volumes: "%{hiera('service_volumes')}"
